post http://localhost:3003/api/login/
Content-Type: application/json

    {
        "username": "bloodthirstycat21",
        "pass": "bloodthirstycat21"
    }

###
post http://localhost:3003/api/users/
Content-Type: application/json

    {
        "name": "Angus",
        "username": "bloodthirstycat21",
        "pass": "bloodthirstycat21"
    }
###
post http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb29kdGhpcnN0eWNhdDIxIiwiaWQiOiI1ZTI4ODM4NDFjYzYxYjFkNjA0ZGFjNGUiLCJpYXQiOjE1Nzk3MTM0NDN9.wqmBwrk80JfTk6n_dyW11Fj5Y39vLxOHbdcUsfDHlyk
    
    {
        "title": "Angus 2nd blog",
        "author": "Angus Angstius",
        "url": "www.angusangustius.com",
        "likes": 29
    }